### ISSUE TITLE
VersionNotCompatible

### ISSUE THREAD

**Issue by gitSunic** [agusmakmun/django-markdown-editor#101]
I dont understand what happeded. I just tried to run martor with a clear project, but have a problem in admin. I cant preview description in a Post(like in Demo) because 'raise VersionNotCompatible("The markdown isn't compatible, please reinstall "martor.utils.VersionNotCompatible: The markdown isn't compatible, please reinstall your python markdown into Markdown>=3.0'. But i already have 3.1.1. So i dont know how to solve it (

**Comment by koenw** [comment]
I ran into the same issue today, except the error you quote (`The markdown isn't compatible, please reinstall` happens during the handling of another error; which  is `ModuleNotFoundError: No module named 'django.contrib.staticfiles.templatetags'`.

The Django 3 release notes mention the removal of the `templatetags` module, so I believe it all comes down to *django-markdown-editor* not yet being compatible with Django 3.

**Comment by koenw** [comment]
Hmm, a `grep templatetags` taught me the `templatetags` module is only used in the *emoji* plugin (I presume to serve the emoji's as static files), so disabling the *emoji* plugin serves as a workaround.

**Comment by BenjaminPalko** [comment]
I've made a PR to fix this #109
