### ISSUE TITLE
Travis CI Build Fails For Python 2.7

### ISSUE THREAD

**Issue by CristopherH95** [agusmakmun/django-markdown-editor#112]
The Travis CI build appears to fail in Python 2.7 due to an import error from `markdown`. The error raised is:

```
ImportError: A recent version of Python 3 is required.
```

See the job logs from #111 for an example of this.

**Comment by elmcrest** [comment]
if this would be my project I'd just give this a `wontfix` label and close it, no offense :)

**Comment by CristopherH95** [comment]
None taken. I only brought this up because the package is still tested under Python 2, which `markdown` no longer supports. If this is not an issue or a concern, then by all means this issue should be closed.

**Comment by elmcrest** [comment]
I see. Nice move!

**Comment by CristopherH95** [comment]
Python 2 removed from tests in #111.
