### ISSUE TITLE
When I use {{ }} in the editor this renders an empty page.

### ISSUE THREAD

**Issue by rasulkireev** [agusmakmun/django-markdown-editor#115]
When I use the following code block:

```python
{% for post in posts %}
  <a href="{% url 'post' post.pk %}">
      <p>{{ post.title }}</p>
  </a>
{% endfor %}
```

The results is an empty page. 

This is how I use it in the template:

```
{{ post.body | safe_markdown }}
```

I'm not sure how to bypass that. Should I use some sort of escape character in front of the {{ }} symbols? 

Thanks a ton in advance.

**Comment by rasulkireev** [comment]
I've solved the initial problem by adding `\` before the curly brace:

```python
\{% for post in posts %\}
  <a href="\{% url 'post' post.pk %\}">
      <p>\{\{ post.title \}\}</p>
  </a>
\{% endfor %\}
```
Unfortunately, that block is rendered with backlashes. I want to have the block to look like in the message above.

**Comment by agusmakmun** [comment]
@rasulkireev Based on your problem, perhaps have a problem from python [`markdown`](https://pypi.org/project/Markdown/) itself.
As you can see, in [this line](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/utils.py#L31) we just follow the rule of [python markdown](https://pypi.org/project/Markdown/).

```python
return markdown.markdown(
    markdown_content,
    safe_mode=MARTOR_MARKDOWN_SAFE_MODE,
    extensions=MARTOR_MARKDOWN_EXTENSIONS,
    extension_configs=MARTOR_MARKDOWN_EXTENSION_CONFIGS
)
```
