### ISSUE TITLE
live preview not showing up in django admin

### ISSUE THREAD

**Issue by sodrooome** [agusmakmun/django-markdown-editor#120]
Hi, i found a problem here. 

during production (i deployed on pythonanywhere), the preview editor doesn't appear in django admin, but it works fine if i run it on local. I've already collect martor's static and i've convinced that the path to static martor directory is correct but, still the preview editor doesnt work.

**Comment by sodrooome** [comment]
Sadly no, i tried many ways but it still hasn't change anything at all

**Comment by serranoarevalo** [comment]
I fixed it by creating a middleware! Thanks anyways!

**Comment by agusmakmun** [comment]
@serranoarevalo can you show me your middleware here please, so it can help anyone later on.

**Comment by serranoarevalo** [comment]
@agusmakmun 

```py
def no_csfr(get_response):
    def middleware(request):

        if "martor" in request.path:
            setattr(request, "_dont_enforce_csrf_checks", True)

        response = get_response(request)

        return response

    return 
```

Don't forget to include it on your settings.py
