### ISSUE TITLE
Is it possible to only support certain markdown (i.e. remove buttons from the text editor)

### ISSUE THREAD

**Issue by matt-dalton** [agusmakmun/django-markdown-editor#124]
I've tried changing the `MARTOR_ENABLE_CONFIGS` from the Readme, but this doesn't seem to actually remove the option from the editor. e.g. Even with emoji and imgur as false I can still press the buttons here:

<img width="610" alt="Screenshot 2020-07-15 at 12 31 57" src="https://user-images.githubusercontent.com/22496337/87540225-33d24100-c697-11ea-93bf-628f5db1888b.png">

It would be good to be able to support certain types of markdown (e.g. h1, h1, p, bold, italics) and have the others removed from the options. This would make it much clearer to people using the widget what markdown they can expect to be rendered.

Does anything like this exist?

**Comment by agusmakmun** [comment]
thank you @matt-dalton for your great idea :+1: 
It already added on [newest version v1.5.0](https://pypi.org/project/martor/1.5.0/), you can now install it by following:

```
pip install martor==1.5.0
```

```python
# To show the toolbar buttons
MARTOR_TOOLBAR_BUTTONS = [
    'bold', 'italic', 'horizontal', 'heading', 'pre-code',
    'blockquote', 'unordered-list', 'ordered-list',
    'link', 'image-link', 'image-upload', 'emoji',
    'direct-mention', 'toggle-maximize', 'help'
]
```

**Comment by matt-dalton** [comment]
Wow....very fast work!

Thanks!
