### ISSUE TITLE
Custom user model

### ISSUE THREAD

**Issue by itssandeep** [agusmakmun/django-markdown-editor#13]
Hi. 

Is it possible to specify a different user model for the mentions without forking the repository and manually changing it?

**Comment by agusmakmun** [comment]
you need to create manually your own extention with following this [mention.py](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/extensions/mention.py).

And then, register the extention into:

```
MARTOR_MARKDOWN_EXTENSIONS = [
    ....

    'martor.extensions.mention', # require for mention
    'martor.extensions.emoji',   # require for emoji
    'yourapp.custom_mention',
]
```

**Comment by itssandeep** [comment]
Hi sorry for the delay in getting back. Thank you, this worked as it should.

**Comment by agusmakmun** [comment]
you're welcome.. :+1:

**Comment by eriktelepovsky** [comment]
Wouldn't be better to use [settings.AUTH_USER_MODEL](https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-AUTH_USER_MODEL) setting or [get_user_model()](https://github.com/django/django/blob/d79cf1e9e2887aa12567c8f27e384195253cb847/django/contrib/auth/__init__.py#L157) helper?
