### ISSUE TITLE
User search should use User.USERNAME_FIELD to allow custom user models

### ISSUE THREAD

**Issue by honi** [agusmakmun/django-markdown-editor#134]
Currently the user search view is assuming that the User model has a [username](https://github.com/agusmakmun/django-markdown-editor/blob/54aed6d17a93135a5dec0eca67230e20710ee153/martor/views.py#L63) field.

It could instead use `User.USERNAME_FIELD` to allow custom user models where the username field has been replaced by something else.

Something like this:
```python
users = User.objects.filter(**{f'{User.USERNAME_FIELD}__icontains': username}).filter(is_active=True)
```

**Comment by agusmakmun** [comment]
@honi nice idea.
