### ISSUE TITLE
Unable to set preview option as a tab near "editor"

### ISSUE THREAD

**Issue by astrosetup** [agusmakmun/django-markdown-editor#139]
Hello,

I'm using MartorFormField() on my form and using the default template provided on the github homepage of this project.

I'm unable to get a preview tab to show us in a separate tab in the toolbar, the preview tab is by default shown below the ace editor. 

How can i move the preview into its own separate preview tab as shown in following photo.

https://github.com/agusmakmun/django-markdown-editor/blob/master/.etc/images/semantic/martor-editor.png?raw=true

Mine looks like this:
https://prnt.sc/uxqhw2

**Comment by agusmakmun** [comment]
@astrosetup you should change `living` to `"false"` inside `MARTOR_ENABLE_CONFIGS`.

```
MARTOR_ENABLE_CONFIGS = {
    'emoji': 'true',        # to enable/disable emoji icons.
    'imgur': 'true',        # to enable/disable imgur/custom uploader.
    'mention': 'false',     # to enable/disable mention
    'jquery': 'true',       # to include/revoke jquery (require for admin default django)
    'living': 'false',      # to enable/disable live updates in preview
    'spellcheck': 'false',  # to enable/disable spellcheck in form textareas
    'hljs': 'true',         # to enable/disable hljs highlighting in preview
}
```

**Comment by astrosetup** [comment]
That works. Thanks.
