### ISSUE TITLE
Form label empty in Django Admin

### ISSUE THREAD

**Issue by MickaelWalter** [agusmakmun/django-markdown-editor#14]
When having several MartorFormField in the same form (and thus Django Admin interface, otherwise I would have integrated it in my own template), it is difficult to identify what is the role of each field because the label is emptied at the field creation (see [fields.py](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/fields.py) line 12) : 

    class MartorFormField(forms.CharField):

    def __init__(self, *args, **kwargs):
        kwargs['label'] = ''  # To set without label.
        super(MartorFormField, self).__init__(*args, **kwargs)

        if not issubclass(self.widget.__class__, MartorWidget):
            self.widget = MartorWidget()

Is it possible to remove this instruction to let the choice to the user ? I patched the code in my project but for maintainability it would be better if this could be integrated in the main branch.

Anyway kudos for this helpful library !

**Comment by agusmakmun** [comment]
Good catch :+1:, I has updated the version to [v1.2.5](https://github.com/agusmakmun/django-markdown-editor/releases/tag/v1.2.5), wich simply configuration in the `settings.py`:

```
# To setup the martor edito with label or not (default is False)
MARTOR_ENABLE_LABEL = False
```

You can re-install via pip to get the latest version.

**Comment by MickaelWalter** [comment]
Just tested with the latest version, it works :)

Thank you !
