### ISSUE TITLE
Error link .com.xx

### ISSUE THREAD

**Issue by RodrigoHernan** [agusmakmun/django-markdown-editor#143]
Break when i like create link with .com.xx

If i wrote `[link.com.ar](http://link.com.ar)` render ->  [link.com](http://link.com).ar 

see video for details https://www.loom.com/share/d44791e736204ecfb266faa02bd5b267

**Comment by agusmakmun** [comment]
we using [`martor/extensions/urlize.py`](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/extensions/urlize.py) to render the links. Seems your `link.com.ar` doesn't includes in common domains name.

```python
URLIZE_RE = '(%s)' % '|'.join([
    ....
    r'[^(<\s]+\.(?:com|net|org)\b',
]
```

I'm trying to use default `django.utils.html.urlize` and he also found the same result:

```python
>>> from django.utils.html import urlize
>>>
>>> urlize('google.com')
'<a href="http://google.com">google.com</a>'
>>>
>>> urlize('https://google.com')
'<a href="https://google.com">https://google.com</a>'
>>>
>>> urlize('fooba@gmail.com')
'<a href="mailto:fooba@gmail.com">fooba@gmail.com</a>'
>>>
>>> urlize('link.com.ar')
'link.com.ar'
>>>
>>> urlize('python.web.id')
'python.web.id'
```
