### ISSUE TITLE
Some versions of requests import insecure urllib3 versions.

### ISSUE THREAD

**Issue by kitsunde** [agusmakmun/django-markdown-editor#144]
Which seem to have been resolved in 2.25.0: https://github.com/psf/requests/pull/5651

```
martor==1.5.7
  - Django [required: Any, installed: 2.2.15]
    - pytz [required: Any, installed: 2020.4]
    - sqlparse [required: >=0.2.2, installed: 0.4.1]
  - Markdown [required: Any, installed: 3.0.1]
  - requests [required: Any, installed: 2.20.0]
    - certifi [required: >=2017.4.17, installed: 2020.11.8]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.8, installed: 2.7]
    - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.3]
```

It would be helpful if this would depend on `requests>=2.25.0` since now everyone needs to pin requests even if it doesn't get used.

**Comment by agusmakmun** [comment]
@kitsunde please update your martor version, meanwhile our martor always use the newest version for [requirements](https://github.com/agusmakmun/django-markdown-editor/blob/master/requirements.txt):

```
Django
Markdown
requests
```
