### ISSUE TITLE
Misleading error/exception thrown with invalid data .

### ISSUE THREAD

**Issue by rgammans** [agusmakmun/django-markdown-editor#147]
When unexpected errors occur in the markdownify, or function which rely on it the martor.utils.VersionNotCompatible, exception
is thrown rather than propagating the original exception.  I generally feel that pattern try-except in markdownify eg..
```
  try:
     .
     .
 except Exception:
   .
```
has too broad a 'catch' clause.

Can you consider narrowing the clause?

## Details
- Browser and browser version: No Browser, server-side issue.
- OS version: Debian 10.
- Martor version: 1.5.8

### Steps to reproduce
(minimal example)
1. Start a clean directory.
2. `pipenv install martor`
3. create settings.py
```
SECRET_KEY="qaswejuiokl" # anything to make django happy.
```
4. create test.py
```
import os
os.environ['DJANGO_SETTINGS_MODULE']='settings'
import martor.utils as utils

print(utils.markdownify(None))
```
5. `pipenv run python test.py`

**Comment by rgammans** [comment]
I suggest a patch along these lines
```diff
--- a/martor/utils.py
+++ b/martor/utils.py
@@ -33,7 +33,9 @@ def markdownify(markdown_content):
             extensions=MARTOR_MARKDOWN_EXTENSIONS,
             extension_configs=MARTOR_MARKDOWN_EXTENSION_CONFIGS
         )
-    except Exception:
+    except TypeError as e:
+        if 'extendMarkdown' not in str(e):
+            raise
         raise VersionNotCompatible("The markdown isn't compatible, please reinstall "
                                    "your python markdown into Markdown>=3.0")


```

**Comment by agusmakmun** [comment]
@rgammans oh ok, nice one. can you please create new P.R?

**Comment by rgammans** [comment]
Ok, I can do this. Do I need to add a unit test? there doesn't seem to be very many in this project as it stands at the moment

**Comment by agusmakmun** [comment]
@rgammans no need unitest is no problem.
