### ISSUE TITLE
Broken design in admin page

### ISSUE THREAD

**Issue by niturk** [agusmakmun/django-markdown-editor#148]
martor breaks the design of the admin page

## Details
- Browser and browser version: Chrome  88
- OS version: Django 3.1.5
- Martor version: 1.5.8

### Steps to reproduce

1. I can't edit the page with fieldsets
2. `classes ': (' wide ',' extrapretty ') ` code like this doesn't work
3. i didnt override all textfield widget to martor. I'm using more than one textfield I don't want all of them to change
4. I cannot group form elements horizontally.

at the same time half of the delete button is visible
![Screen Shot 2021-01-31 at 11 34 47 PM](https://user-images.githubusercontent.com/3787035/106397135-eba12300-641c-11eb-9a93-4508757eb6e7.png)

### My Martor Configs

```python
MARTOR_THEME = 'bootstrap'
MARTOR_ENABLE_CONFIGS = {
    'emoji': 'true',  # to enable/disable emoji icons.
    'imgur': 'true',  # to enable/disable imgur/custom uploader.
    'mention': 'false',  # to enable/disable mention
    'jquery': 'true',  # to include/revoke jquery (require for admin default django)
    'living': 'false',  # to enable/disable live updates in preview
    'spellcheck': 'false',  # to enable/disable spellcheck in form textareas
    'hljs': 'true',  # to enable/disable hljs highlighting in preview
}
MARTOR_TOOLBAR_BUTTONS = [
    'bold',
    'italic',
    'horizontal',
    'heading',
    'pre-code',
    'blockquote',
    'unordered-list',
    'ordered-list',
    'link',
    'image-link',
    'image-upload',
    'emoji',
    'direct-mention',
    'toggle-maximize',
    'help',
]


MARTOR_UPLOAD_PATH = 'images/uploads/{}'.format(time.strftime("%Y/%m/%d/"))
MARTOR_UPLOAD_URL = '/api/uploader/'  # change to local uploader
#Maximum Upload Image
#2.5MB - 2621440
MAX_IMAGE_UPLOAD_SIZE = 102400  # 100kb
```

**Comment by AnderUstarroz** [comment]
Same here, Martor editor is broken on admin panels for **Django 3.1.6**

**Comment by agusmakmun** [comment]
@AnderUstarroz @niturk

- [x] Fixed in this commit: https://github.com/agusmakmun/django-markdown-editor/commit/3a2d6035b06771fd8ecb4326442b9f6564f55103

Please upgrade the version `pip install martor --upgrade`

**Comment by niturk** [comment]
the bug has not been fixed yet, i cant display fields with inline.
```python
fieldsets = (
        (
            None,
            {
                'fields': (
                    (
                        'status',
                        'published_at',
                    ),
                    'title'
                ),
            },
        ),
        # (
        #     'Content',
        #     {'fields': ('content',)},       # martor
        # ),
    )
```
does not work when martor editor is active.
