### ISSUE TITLE
 i cant display fields with inline - django admin

### ISSUE THREAD

**Issue by niturk** [agusmakmun/django-markdown-editor#152]
the bug has not been fixed yet, i cant display fields with inline. #148 
```python
fieldsets = (
        (
            None,
            {
                'fields': (
                    (
                        'status',
                        'published_at',
                    ),
                    'title'
                ),
            },
        ),
        # (
        #     'Content',
        #     {'fields': ('content',)},       # martor
        # ),
    )
```
does not work when martor editor is active.

## Details
- OS (Operating System) version: MacOS
- Browser and browser version: Chrome 89
- Django version: 3.1.7
- Martor version: 1.6.0

**Comment by agusmakmun** [comment]
@niturk what your martor theme now?

**Comment by agusmakmun** [comment]
Seems it same with `admin.TabularInline`

![image](https://user-images.githubusercontent.com/7134451/110869760-a7e3e800-82fd-11eb-92fd-c025ca9ce2c9.png)

**Comment by niturk** [comment]
@agusmakmun i m using bootstrap theme

without martor
![without_martor](https://user-images.githubusercontent.com/3787035/110894879-bfc16900-8309-11eb-94bc-c0ecff067168.png)

with martor
![with_martor](https://user-images.githubusercontent.com/3787035/110894902-c94ad100-8309-11eb-88a3-9b7fd253183c.png)

**Comment by dismine** [comment]
It seems I am experiencing the same bug. The last version that works in my case 1.5.1. As soon as I disable `AdminMartorWidget` everything work again.

**Comment by agusmakmun** [comment]
@niturk @dismine 

I just know it blocked by the newest bootstrap css. after I updated it to `display: revert` it working fine.
I'll update this to newest version.

![image](https://user-images.githubusercontent.com/7134451/113524730-beb6eb00-95da-11eb-82fb-fa70fec46a87.png)
