### ISSUE TITLE
Why are there two forms showing on the default demo app?

### ISSUE THREAD

**Issue by shanerowden** [agusmakmun/django-markdown-editor#153]
![image](https://user-images.githubusercontent.com/46952819/113582883-88836680-95ee-11eb-8b5e-e079839f4aff.png)

**Comment by agusmakmun** [comment]
@shanerowden to resolve Multiple Fields issue #3, the first form is used for [`{{ form.description }}` and the second for `{{ form.wiki }}`](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor_demo/app/templates/bootstrap/form.html#L16-L21). meanwhile you can also use a single editor form.
