### ISSUE TITLE
martor's css overrides label "display" property and breaks django admin layouts

### ISSUE THREAD

**Issue by immerrr** [agusmakmun/django-markdown-editor#156]
## Details
- OS (Operating System) version: Ubuntu 20.04
- Browser and browser version: Chromium 90.0
- Django version: 3.2
- Martor version & theme:  1.6.2, default theme

### Steps to reproduce

1. Configure and activate a virtualenv (here, with poetry)

```
$ cat pyproject.toml 
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["immerrr <immerrr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2"
martor = "^1.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

$ poetry env use python
$ poetry install
$ poetry shell
```

2. `$ django-admin startproject martorbug .`
3. `./manage.py startapp core`
4. add 'core' and 'martor' to `INSTALLED_APPS` in `martorbug/settings.py`
5. add two models

```
$ cat core/models.py 
from django.db import models
from martor.models import MartorField

# Create your models here.


class Foobar(models.Model):
    name = models.TextField()


class ModelWithFK(models.Model):
    name = models.TextField()
    description = MartorField()
    foobar = models.ForeignKey(Foobar, on_delete=models.CASCADE)

```

6. register models with admin

```
$ cat core/admin.py 
from django.contrib import admin


from .models import Foobar, ModelWithFK

# Register your models here.


@admin.register(Foobar)
class FoobarAdmin(admin.ModelAdmin):
    fields = ['name']


@admin.register(ModelWithFK)
class ModelWithFKAdmin(admin.ModelAdmin):
    fields = ['name', 'foobar', 'description']
```

7. `./manage.py createsuperuser --username user --email user@example.org` (with some password)
8. add 'STATIC_ROOT' to settings, run `./manage.py collectstatic`
9. `./manage.py runserver`
10. create a foobar via admin
11. try creating a "model with fk"
12. observe how a FK dropdown shows the label on the right hand side:

![image](https://user-images.githubusercontent.com/579798/116040663-987deb80-a66c-11eb-8a2a-831553d20a1b.png)

13. disable the `display` property for `fieldset .form-row div>label` selector (that comes from martor.min.css) and notice how the labels are displayed correctly now:

![image](https://user-images.githubusercontent.com/579798/116040447-55237d00-a66c-11eb-9b74-7b6a368b4aff.png)

**Comment by zemogle** [comment]
I also have this problem.  It is overriding the `display:block;` from the default Django `admin.css`. I'm using the `semantic` theme and I don't notice any change in `TextField` UI when I use dev tools to disable the `display` property.

**Comment by agusmakmun** [comment]
@zemogle @immerrr already fixed, please upgrade your martor:

```
pip install django-markdown-editor --upgrade
```

![image](https://user-images.githubusercontent.com/7134451/121795460-53714100-cc3b-11eb-9eaa-caad115b62c5.png)
