### ISSUE TITLE
Uploaded image not rendering

### ISSUE THREAD

**Issue by HussamCheema** [agusmakmun/django-markdown-editor#162]
- Django version: 3.2.4
- Martor version: 1.6.3

When I upload the image, it get saved in the media folder. The path of the image is like this:

**"/media/images/uploads/2021/06/26/ce63d20809-compressor.jpg"**

But it's not rendering on the html webpage. I'm getting this output on my webpage:

![image](https://user-images.githubusercontent.com/17239812/123505262-7eb25200-d677-11eb-9965-44648086a01f.png)

I have also set the url paths for static and media folder:

![image](https://user-images.githubusercontent.com/17239812/123505279-9b4e8a00-d677-11eb-94ec-912ca8721db2.png)

**Comment by HussamCheema** [comment]
I forgot to put "=" after "+" in "urlpatterns" while appending static url and media url.

**Comment by agusmakmun** [comment]
ya, it should be:

```
urlpatterns += static(...)
```
