### ISSUE TITLE
Help button: TypeError: e(...).modal is not a function

### ISSUE THREAD

**Issue by Vayel** [agusmakmun/django-markdown-editor#164]
Hi!

When I click on the help button of the admin integration, nothing happens and I get this error in the JS console:

```
Uncaught TypeError: e(...).modal is not a function (martor.bootstrap.min.js:8:13110)
```

## Details
- OS (Operating System) version: Windows 10
- Browser and browser version: Firefox 89.0.2 (64-bit)
- Django version: 3.1.6
- Martor version & theme: 1.6.3 Bootstrap

### Steps to reproduce

```python
# settings.py

MARTOR_ENABLE_LABEL = True
MARTOR_ENABLE_CONFIGS = {
    "emoji": "false",
    "imgur": "false",
    "mention": "false",
    "jquery": "true",
    "living": "false",
    "spellcheck": "false",
    "hljs": "false",
}

MARTOR_TOOLBAR_BUTTONS = [
    "bold",
    "italic",
    "heading",
    "unordered-list",
    "ordered-list",
    "link",
    "toggle-maximize",
    "help",
]
```

```python
# models.py

from django.db import models
from martor.models import MartorField


class MyModel(models.Model):
    content = MartorField()
```

```python
```python
# admin.py

from django.contrib import admin

from .models import MyModel


@admin.register(MyModel)
class MyModelAdmin(admin.ModelAdmin):
    pass
```

Is https://jquerymodal.com/ missing?

Thanks!

**Comment by agusmakmun** [comment]
@Vayel have you collected your static files?

```
./manage.py collectstatic
```

if yet, then you should do it first, and makesure the path of `/static/plugins/js/jquery.min.js` is found in your browser.

**Comment by Vayel** [comment]
@agusmakmun thanks for the quick answer! Yes I did and I can access `/static/plugins/js/jquery.min.js`. I cant' find any instance of "modal" in the jquery code though.

**Comment by agusmakmun** [comment]
@Vayel have you tried also to upgrade your martor?

```
pip install martor --upgrade
```

**Comment by mnieber** [comment]
@agusmakmun I have the same problem (I'm on version 1.6.13). Where is the `modal` function supposed to come from? Like the OP, I cannot see a `modal` function in any of the loaded dependencies.
