### ISSUE TITLE
XSS using javascript: URLs

### ISSUE THREAD

**Issue by wfinn** [agusmakmun/django-markdown-editor#167]
javascript: urls can cause cross site scripting

### Steps to reproduce

1. paste this in your editor `[aaaa](javascript:alert(1))`
2. preview it
3. click on aaaa

The fix would be only allowing https?:// urls or maybe a small whitelist.

**Comment by agusmakmun** [comment]
Thank you @wfinn for reporting this issue.
The same issue on official: https://github.com/Python-Markdown/markdown/issues/976

Probably we should implement a `bleach` to handle that case.
but, I still struggle on rendering `iframe` and `img`.

**Comment by agusmakmun** [comment]
@wfinn seems we have a solution for you https://github.com/netbox-community/netbox/issues/4717#issuecomment-646041346

```python
# Render Markdown
html = markdown(value, extensions=['fenced_code', 'tables'])

class MyHTMLParser(HTMLParser):
    error = False
    def handle_starttag(self, tag, attrs):
        for key, val in attrs:
            if tag == 'a' and key == 'href':
                for scheme in settings.ALLOWED_URL_SCHEMES:
                    if val.startswith(scheme):
                        return
                self.error = True
            
parser = MyHTMLParser()
parser.feed(html)
if (parser.error):
    html = "A link with an invalid scheme was detected - see settings.ALLOWED_URL_SCHEMES"

return mark_safe(html)
```

**Comment by agusmakmun** [comment]
@wfinn fixed on this version: https://pypi.org/project/martor/1.6.8/
please upgrade your martor;

```
pip install martor --upgrade
```

**Comment by wfinn** [comment]
Hi,
I noticed while `[aaaa](javascript:alert(1))` is filtered, `[aaaa](javascript&colon;alert(1))` is not, it still results in `<a href="javascript:alert(1)>aaaa</a>`

**Comment by agusmakmun** [comment]
@wfinn hmm challanging, the patterns should be:

```
pattern = fr"\[(.+)\]\((?!({schemes})).*(:|;)(.+)\)"
```

Here is the test:

```
import re


markdown_text = """
[aaaa](javascript:alert(1))

[aaaa](javascript&colon;alert(1))
"""

ALLOWED_URL_SCHEMES = [
    "file", "ftp", "ftps", "http", "https", "irc", "mailto",
    "sftp", "ssh", "tel", "telnet", "tftp", "vnc", "xmpp",
]

schemes = "|".join(ALLOWED_URL_SCHEMES)
pattern = fr"\[(.+)\]\((?!({schemes})).*(:|;)(.+)\)"
markdown_text = re.sub(
    pattern,
    "[\\1](\\3)",
    markdown_text,
    flags=re.IGNORECASE,
)
```

output:

```
\n[aaaa](:)\n\n[aaaa](;)\n
```
