### ISSUE TITLE
Compatibility issue with Django 4.0 ->  cannot import name 'force_text'

### ISSUE THREAD

**Issue by lopify** [agusmakmun/django-markdown-editor#169]
I'm trying to use martor with Django 4.0 but I get this error when running the Django app:

ImportError raised when trying to load 'martor.templatetags.martortags': cannot import name 'force_text' from 'django.utils.encoding'

## Details
- Django version: 4.0
- Martor version & theme: 1.6.4

### Steps to reproduce

1. Setup a new Django 4.0 project 
2. Add martor to the installed apps
3. ./manage.py runserver
4. ImportError: cannot import name 'force_text' from 'django.utils.encoding'

**Comment by XaiDoee** [comment]
Same Problem !

**Comment by soomy** [comment]
'force_text' was deprecated back in 3.0; it seems to work for Django 4.0 by using force_str instead (see pr #170)

**Comment by Peppar** [comment]
1.6.6 seems to uncover another deprecated function (at least on my install) in `martor/views.py:6`: 

`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'`

It's now called just `gettext_lazy`

**Comment by agusmakmun** [comment]
@lopify @Peppar both issues has been resolved, please upgrade your martor:

```
pip install martor --upgrade
```
