### ISSUE TITLE
Change image

### ISSUE THREAD

**Issue by muradaliyev88** [agusmakmun/django-markdown-editor#18]
how can I change the size of an image using Markdown?

**Comment by agusmakmun** [comment]
Currently we use common markdown syntax, I'll appreciate if you found this method.

**Comment by kewellcjj** [comment]
You could do
```
![w50p](url)
```
then
```css
img[alt=w50p] { width: 50%; } 
```
in css. Worked in my case, see [https://stackoverflow.com/a/14747656/11073497](https://stackoverflow.com/a/14747656/11073497)

**Comment by agusmakmun** [comment]
or, by using this syntax
```
![image-alt](url){height=100px}
```

or 

```
![image-alt](url){style="border: 1px solid;height:100px"}
```
