### ISSUE TITLE
How to embed HTML in Markdown

### ISSUE THREAD

**Issue by enjoy-software** [agusmakmun/django-markdown-editor#181]
# Is there a suggested way to embed HTML in Markdown

<img width="1167" alt="截圖 2022-05-10 下午4 23 25" src="https://user-images.githubusercontent.com/100591266/167583690-467e9905-f038-43f4-99ab-b5ac9567976b.png">

Something like that, but only parse specific tag is better.

For example
input:
```
<div>Hello World</div>
<html><div>Hello World<div></html>
```

output:
```
<div>Hello World</div>
Hello World
```

This is my way to embed HTML

```
settings.py

# Markdown extensions (default)
MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.fenced_code',

    # Custom markdown extensions.
    'martor.extensions.urlize',
    'martor.extensions.del_ins',      # ~~strikethrough~~ and ++underscores++
    'martor.extensions.mention',      # to parse markdown mention
    'martor.extensions.emoji',        # to parse markdown emoji
    'martor.extensions.mdx_video',    # to parse embed/iframe video
    'martor.extensions.escape_html',  # to handle the XSS vulnerabilities
]
# apend md_in_html extension
MARTOR_MARKDOWN_EXTENSIONS.append('markdown.extensions.md_in_html')
```

**Comment by agusmakmun** [comment]
Hello @enjoy-software, now you can use embed html in markdown by upgrading your martor:

```
pip install martor --upgrade
```

Then add your custom tag in `settings.ALLOWED_HTML_TAGS`, for example in your case is a `"div"`:

```python
ALLOWED_HTML_TAGS = [
    "a", "abbr", "b", "blockquote", "br", "cite", "code", "command",
    "dd", "del", "div", "dl", "dt", "em", "fieldset", "h1", "h2", "h3", "h4", "h5", "h6",
    "hr", "i", "iframe", "img", "input", "ins", "kbd", "label", "legend",
    "li", "ol", "optgroup", "option", "p", "pre", "small", "span", "strong",
    "sub", "sup", "table", "tbody", "td", "tfoot", "th", "thead", "tr", "u", "ul"
]
```

And then after that append `md_in_html` extension, the same as your code:

```python
MARTOR_MARKDOWN_EXTENSIONS.append("markdown.extensions.md_in_html")
```

Here is the result example:

<img width="410" alt="Screen Shot 2022-11-18 at 22 16 40" src="https://user-images.githubusercontent.com/7134451/202738060-46aee238-4775-409b-a04b-2cdf0e249375.png">

<img width="819" alt="Screen Shot 2022-11-18 at 22 17 13" src="https://user-images.githubusercontent.com/7134451/202738170-ac0c3d1a-ca1c-41f4-903e-822bfc0c7b1e.png">
