### ISSUE TITLE
XSS via href content

### ISSUE THREAD

**Issue by Arkango** [agusmakmun/django-markdown-editor#182]
The bug reported here https://github.com/agusmakmun/django-markdown-editor/issues/173 can be extended to an href content with small syntax changes.

### Steps to reproduce

1.  editor insert:  [testlinkxss](\" onmouseover=alert(document.domain) l) 
2. preview will result in: <p><a href="" onmouseover="alert(document.domain)" l"="">testlinkxss</a> </p>
3. go with the mouse over will trigger the payload.

<img width="772" alt="Screenshot 2022-05-23 at 16 25 26" src="https://user-images.githubusercontent.com/23188987/169842804-9c1d4e55-df0c-4ced-b9c9-da07bb805ed5.png">

<img width="1022" alt="Screenshot 2022-05-23 at 16 25 15" src="https://user-images.githubusercontent.com/23188987/169842787-ebcde304-1956-4bb6-8ebc-b81c7bfc3768.png">

**Comment by agusmakmun** [comment]
@Arkango you correct, that's why we marked it as "help wanted"

**Comment by Arkango** [comment]
@agusmakmun I tested the regex https://regex101.com/r/fUvNyq/1 with our payload executed here https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/utils.py#L33 there isn't a match edit the regex to properly identify links and avoid \

**Comment by agusmakmun** [comment]
good catch @Arkango, but as you know here by default all markdown content will be rendered from an existing renderer. So, the only things that we can do is only replacing the vulnerability text, so that's why we did `re.sub(..)` to handle it.

**Comment by Arkango** [comment]
Well if you replace .* and .+ with only valid url characters like this [^-\]_.~!*'();:@&=+$,/?%#[A-z0-9] , look at this solution proposed here https://stackoverflow.com/questions/22038142/regex-for-valid-url-characters no backslash is included

**Comment by agusmakmun** [comment]
@Arkango I still didn't get it, can you please create a pull request, so I can check it out.
