### ISSUE TITLE
Preview fails due to missing CSRF token

### ISSUE THREAD

**Issue by bendavis78** [agusmakmun/django-markdown-editor#184]
When selecting preview tab in admin, it says "Nothing to preview". The console output shows the following::

    WARNING django.security.csrf: Forbidden (CSRF token missing or incorrect.): /martor/markdownify/ 

- Django version: 2.2.12
- Martor version: 1.6.13

**Comment by agusmakmun** [comment]
hello @bendavis78, please add this in your settings:

```
CSRF_COOKIE_HTTPONLY = False
```
