### ISSUE TITLE
safe_markdown throw KeyError exception

### ISSUE THREAD

**Issue by enjoy-software** [agusmakmun/django-markdown-editor#192]
This content throws a KeyError exception when template using safe_markdown

```example.cs
int[] values = new int[] { 0, 12, 44, 36, 92, 54, 13, 8 };
IEnumerable<int> result =
    from v in values
    where v < 37
    orderby -v
    select v;
```

```<div>{{ object.content|safe_markdown }}</div>```

## Details
- OS (Operating System) version: macOS Monterey 12.6.1
- Browser and browser version: 107.0.5304.110 (正式版本) (x86_64)
- Django version: 4.0.2
- Martor version & theme: 1.6.15 bootstrap

### Steps to reproduce

1. Write markdown content as shown above
2. Template output content with safe_markdown filter
3. Browse url with markdown template

<img width="1099" alt="截圖 2022-11-25 上午5 52 29" src="https://user-images.githubusercontent.com/100591266/203867618-0b0ff0a6-acef-4e56-b2dc-7827ac1927d1.png">

**Comment by ron8mcr** [comment]
I've met this problem with such markdown:

``````
```
hello = {'world'}
```
``````

# Details

* Martor demo app, commit d3a6189ccf0a8ce6ad8435902c980feea83c61a7
* Django version: 3.2.18 (because of problems with `tzdata` in newer versions)

![image](https://user-images.githubusercontent.com/7027722/218936987-780a2340-ba39-40d8-a8c9-3dcf2785c80c.png)

**Comment by agusmakmun** [comment]
Hello @enjoy-software, @ron8mcr 

It's now [fixed](https://github.com/agusmakmun/django-markdown-editor/commit/b72bec2233233a09c2332218342e70aa748cc081) on latest version, can you please upgrade your martor package?

```
pip install martor --upgrade
```

**Comment by ron8mcr** [comment]
@agusmakmun it worked, thanks for fixing this!

**Comment by enjoy-software** [comment]
@agusmakmun @ron8mcr Thanks.
