### ISSUE TITLE
resizable.min.js errors (Cannot read properties of undefined) on Django 3.2

### ISSUE THREAD

**Issue by sodrew** [agusmakmun/django-markdown-editor#196]
I get these javascript errors on the admin pages with Martor fields (I have three):

```
Uncaught TypeError: Cannot read properties of undefined (reading 'fn')
    at resizable.min.js:8:16
    at resizable.min.js:8:2064
jquery.js:4055 
       
Uncaught TypeError: e(...).resizable is not a function
    at HTMLDivElement.<anonymous> (martor.bootstrap.min.js:8:2089)
    at Function.each (jquery.js:381:19)
    at jQuery.fn.init.each (jquery.js:203:17)
    at e.fn.martor (martor.bootstrap.min.js:8:351)
    at HTMLDocument.<anonymous> (martor.bootstrap.min.js:8:14606)
    at mightThrow (jquery.js:3762:29)
    at process (jquery.js:3830:12)
```

I followed the directions for setup:
```
class YourModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': AdminMartorWidget},
    }
```

I found that using the latest jquery, not the jquery that django 3.2 defaults to, fixes it.
```
class YourModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': AdminMartorWidget},
    }
    class Media:
        js = ("jquery/dist/jquery.min.js",)

```

My guess is that this is an issue with the default jquery on django 3.2

## Details
- OS (Operating System) version: Windows 11
- Browser and browser version: MS Edge 108.0.1462.76 (Official build) (64-bit)
- Django version: 3.2 (my webhost won't upgrade to 4.x)
- Martor version & theme: 1.6.16 

### Steps to reproduce

1. Create a model with three fields
2. Follow the config directions: https://github.com/agusmakmun/django-markdown-editor
3. Go to the admin page (e.g., localhost:8000/admin/)  for this model
4. View javascript errors

**Comment by agusmakmun** [comment]
We tried it, and didn't found any error;

![Screen Shot 2023-02-02 at 22 23 46](https://user-images.githubusercontent.com/7134451/216366276-51a89141-375e-448e-b06e-7161a7d1fd37.png)

![Screen Shot 2023-02-02 at 22 24 06](https://user-images.githubusercontent.com/7134451/216366376-4b23b7cb-5a45-4e23-9094-139c35d2199c.png)


Probably I'll suggest you to custom your own jQuery script to handle that issue.

**Comment by sodrew** [comment]
OK, I narrowed it down to this setting:

```
MARTOR_ENABLE_CONFIGS = {
    'jquery': 'false',       # to include/revoke jquery (require for admin default django)
}

```
My apologies, I must have been playing around with settings because I was seeing issues with bootstrap when I first merged it in and forgot to change this back.

For anyone else, if you are using a separate jquery and need to set this to false, but do want this to work in django admin, then just add the media class specifying the path to your jquery version to your model admin:

```
class YourModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': AdminMartorWidget},
    }
    class Media:
        js = ("jquery/dist/jquery.min.js",)

```
