### ISSUE TITLE
martor markdownify is vulnerable to stored XSS.

### ISSUE THREAD

**Issue by GiJ03** [agusmakmun/django-markdown-editor#200]
While testing an application, I observed that the application was using `martor markdownify`. On further investigation, I observed that `martor markdownify` is vulnerable to stored XSS vulnerability.

Will I be eligible for a CVE, if I report that?

**Comment by some1ataplace** [comment]
Maybe something like this. I did not test this yet. 

To fix the XSS vulnerability, you need to sanitize the user input before rendering it as HTML. One way to do this is by using a library like bleach to clean the input and remove any potentially harmful content.

https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/utils.py

```
import bleach
from django.utils.safestring import mark_safe
from martor import settings
from markdown import markdown


ALLOWED_TAGS = bleach.sanitizer.ALLOWED_TAGS + ['img', 'p', 'pre', 's', 'u', 'code', 'kbd', 'br']
ALLOWED_ATTRIBUTES = bleach.sanitizer.ALLOWED_ATTRIBUTES
ALLOWED_ATTRIBUTES.update({
    '*': ['class', 'id'],
    'img': ['src', 'alt', 'title'],
    'a': ['href', 'rel', 'title'],
})

def markdownify(markdown_text):
    """
    Convert markdown to html.
    """
    html = markdown(text, extensions=settings.MARTOR_MARKDOWN_EXTENSIONS)
    sanitized_html = bleach.clean(html, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES)
    return mark_safe(sanitized_html)
```

**Comment by GiJ03** [comment]
For reporting a valid issue, will I be eligible for a CVE?

**Comment by GiJ03** [comment]
You can find the commonly used XSS payloads below:

https://raw.githubusercontent.com/payloadbox/xss-payload-list/master/Intruder/xss-payload-list.txt

**Comment by agusmakmun** [comment]
I have tested above payloads, and seems all of them are passed in newest version.
So, I'll close this issue. Let me know if any payloads still facing this xss issue.
