### ISSUE TITLE
Incompatibility with Django 4.2

### ISSUE THREAD

**Issue by aaugustin** [agusmakmun/django-markdown-editor#203]
With Django 4.1.8:

<img width="829" alt="Screenshot 2023-04-15 at 10 09 04" src="https://user-images.githubusercontent.com/788910/232199348-32467b6b-41dd-4034-a8b6-64d329d2472c.png">

With Django 4.2:

<img width="820" alt="Screenshot 2023-04-15 at 10 09 32" src="https://user-images.githubusercontent.com/788910/232199356-a88cfe36-6c52-4339-afc3-015fe7782fd0.png">

This is happening on a very basic install without CSS customization. You should be able to reproduce simply by upgrading Django.

Looking at https://github.com/django/django/commits/4.2/django/contrib/admin/static, I see commits that say "Used CSS flex for..." This suggests significant changes to the admin CSS, which would explain this result.

**Comment by agusmakmun** [comment]
@aaugustin alternatively you can use this css path to fix that css issue:

```
MARTOR_ALTERNATIVE_CSS_FILE_THEME = "fix-martor.css"
```

**Comment by agusmakmun** [comment]
Hello @aaugustin, seems the latest version already fixed.
Kindly to upgrade your martor:

```
pip install martor --upgrade
```

![image](https://github.com/agusmakmun/django-markdown-editor/assets/7134451/8cfaf05b-4b3c-4291-9efb-0224523d005a)

**Comment by aaugustin** [comment]
Thank you.
