### ISSUE TITLE
incompatibility with Python versions below 3.9

### ISSUE THREAD

**Issue by tomaszn** [agusmakmun/django-markdown-editor#207]
`removeprefix` and `removesuffix` are available from Python 3.9.

They were introduced here:

https://github.com/agusmakmun/django-markdown-editor/blob/a140eb5fbaa68ada758ad332e480cf7e78023577/martor/urls.py#L15

They break `martor` on Python 3.8.

What about replacing these usages with more compatible implementations?

**Comment by agusmakmun** [comment]
@tomaszn sounds reasonable, can you please create a PR for this?

**Comment by tomaszn** [comment]
@agusmakmun Here it is. What about including also Python 3.6 (lowest supported version) in the automated tests matrix?

**Comment by agusmakmun** [comment]
@tomaszn, I'm not sure if it will be compatible with the Markdown version or not since we had a collision issue with dependency requirements last time. However, let's test it out in your MR to see if it works or not.

**Comment by tomaszn** [comment]
Running tests on Python 3.6 fails on `urllib3`. Their support ended in [2.0.0 (2023-04-26)](https://github.com/urllib3/urllib3/blob/05b21ca5d29764aae60c72e4e3bfceead0f70f95/CHANGES.rst#removed).

So we can pin `urllib3<2` for Python 3.6, or drop it as it already reached End-Of-Life.

**Comment by agusmakmun** [comment]
@tomaszn I see, maybe to add prefix as well if it using Python 3.6

**Comment by tomaszn** [comment]
@agusmakmun You were right, [Markdown 3.4 requires Python 3.7](https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.4.md).

I locked proper package versions for Python 3.6 and the tests passed. What about merging these changes, releasing the last 1.6 release, and starting 1.7 line:
* without py3.6 support (and my compatibility changes)
* with Markdown 3.4.x

**Comment by agusmakmun** [comment]
thanks @tomaszn for creating that PR, I have bumped the newest version, please upgrade it.
