### ISSUE TITLE
License for emojis

### ISSUE THREAD

**Issue by TheBuky** [agusmakmun/django-markdown-editor#21]
Hello, 

I have a simple question about the emojis used in your markdown extension.
Does the [assets-cdn](https://assets-cdn.github.com/images/icons/emoji/smile.png) used for rendering emojis is under a license ? Can we use it has free ? 

Sincerely.

**Comment by agusmakmun** [comment]
Isn't about the license. This martor doesn't provide it because other reason.

> The emojis are not complete yet, because the religion reason.

But, you can checkout this page [wiki: Custom the emojis](https://github.com/agusmakmun/django-markdown-editor/wiki/Custom-the-emojis).

**Comment by TheBuky** [comment]
Ok thank. I was talk about the possibility to use your emoji source.
