### ISSUE TITLE
Side-by-side Editor and Preview

### ISSUE THREAD

**Issue by eriktelepovsky** [agusmakmun/django-markdown-editor#22]
Hi.

Very nice library. I was using django-markdownx until now but then I saw your app. Great job!

I am wondering if it is possible to show Editor and Preview side-by-side using any existing setting or an easy solution? If not, can you consider such feature, please?

Something like this:

![image](https://user-images.githubusercontent.com/2685808/36634561-b9109c90-19a6-11e8-9acb-eedd36670215.png)

Resource: https://github.com/christopherfouquier/mkeditorjs
Demo: https://www.jqueryscript.net/demo/Feature-rich-WYSIWYG-Markdown-Editor-Plugin-with-jQuery-MKEditor/

**Comment by agusmakmun** [comment]
This concept has been applied for the previous version <= 1.1.8, the screenshot looks like this:

![draceditor-preview](https://user-images.githubusercontent.com/7134451/36635628-39b65f62-19eb-11e8-9292-6f7ec58c73ee.png)

But, the name of both isn't same,
- martor _(now)_
- draceditor _(old)_

You can downgrade it with https://pypi.python.org/pypi/draceditor

**Comment by eriktelepovsky** [comment]
I see. Thank you for your answer. It would be nice to have an option to choose between those 2 usages in the martor as well.
