### ISSUE TITLE
Loosen restriction on importlib-metadata

### ISSUE THREAD

**Issue by matteius** [agusmakmun/django-markdown-editor#222]
Currently unable to upgrade other dependencies due to usage of this library.  Example:

```
INFO:pipenv.patched.pip._internal.resolution.resolvelib.factory:
The conflict is caused by:
    martor 1.6.28 depends on importlib-metadata<4.9
    opentelemetry-api 1.21.0 depends on importlib-metadata==6.8.0; python_version >= "3.8"
```

## Details
- OS (Operating System) version:  all
- Browser and browser version: n/a
- Django version:  4.2
- Martor version & theme:  1.6.28

### Steps to reproduce

1.  pip install opentelemetry-api==1.21.0 martor==1.6.28

**Comment by matteius** [comment]
No, we need the restriction loosened on this package to be able to upgrade further.

**Comment by agusmakmun** [comment]
Hello @matteius @Lemmie101, thank you for reporting this issue.
Kindly to upgrade your martor version:

```
pip install martor --upgrade
```

**Comment by matteius** [comment]
Thankyou, I verified this is fixed.
