### ISSUE TITLE
toolbar nav style issue

### ISSUE THREAD

**Issue by junwenwaynepeng** [agusmakmun/django-markdown-editor#225]
![image](https://github.com/agusmakmun/django-markdown-editor/assets/119043105/639aa4cf-80a5-4729-a91f-14be8825c31c)

1. the full-screen button and back-to-normal button show at the same time on its first load.
2. I'd like to see the toolbar has the same width as the textarea.

**Comment by agusmakmun** [comment]
Hello @junwenwaynepeng, thank you for reporting this issue.

We have fixed the issue, please upgrade your martor:

```
pip install martor --upgrade
```
