### ISSUE TITLE
Losing text when (semi)colons follow links.

### ISSUE THREAD

**Issue by pcraig3** [agusmakmun/django-markdown-editor#229]
Hi there, 

First of all, great library. It's been helping a ton as I'm working on a project to import large documents into an editable web interface. 

However, I've recently stumbled across a bug that I'm not sure how to account for. Some of the text is just disappearing even though it is visible in the markdown preview.

Essentially, when I have a paragraph that contains two or more links, putting a colon or a semicolon in the sentence after the first link seems to completely drop everything after the first link. Here is a video of the behaviour I am seeing. 

![Screen Recording 2023-12-28 at 11 40 47 PM](https://github.com/agusmakmun/django-markdown-editor/assets/2454380/1d5d07e7-8e8b-45e4-a554-0bfa04e5dd3b)

## Details
- OS (Operating System) version: macOS Sonoma 14.2.1
- Browser and browser version: All browsers
- Django version: django = "^4.2.7"
- Martor version & theme: martor = "^1.6.28"

### Steps to reproduce

You can use this sentence to test the behaviour:

```
Citation 1. [footnote 4](#ftnt4) Citation 2. [footnote 5](#ftnt5) Citation 3; [footnote 6](#ftnt6)
```

Citation 3 is visible in the "editor" view but missing in the "preview" view. If you move the semicolon to somewhere in "Citation 2", then it will disappear citations 2 and 3.

**Comment by pcraig3** [comment]
I've been playing with this and I've noticed that colons trigger the same problem but other punctuation marks seem to be okay. There is some interaction between colons and brackets that I can't quite figure out.

```
# editor
Content 1. [abc]() Content 2: Cont)ent 3. 
```

```
# preview
Content 1. <a>abc</a>ent 3.
```

**Comment by agusmakmun** [comment]
This is issue is resolved in the newest version. #232
