### ISSUE TITLE
Adding the widget toolbar into the post editing page

### ISSUE THREAD

**Issue by SkippyHo** [agusmakmun/django-markdown-editor#23]
Hello,  I followed your instruction to apply the changes to my models.py and expected to see the same toolbar in my frontend blog post editor as the one shown in Admin. However it doesn't work (it looks like this: 

<img width="796" alt="screenshot 2018-03-04 23 10 22" src="https://user-images.githubusercontent.com/9547768/36953670-7694e846-2057-11e8-811b-15e6e07f1433.png">

I also tried the suggestions in the [post](https://stackoverflow.com/questions/12097825/specifying-widget-for-model-form-extra-field-django) , still doesn't work.

Here is my code (model.py):

```
## models.py 

from django.db import models
from django.utils import timezone

from martor.models import MartorField

class Post(models.Model): 
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    #text = models.TextField()
    text = MartorField()
    created_date = models.DateTimeField(
                   default=timezone.now)
    published_date = models.DateTimeField(
                    blank=True, null=True)
```
And forms.py

```
## forms.py
from django.forms import ModelForm

from martor.fields import MartorFormField
from martor.widgets import AdminMartorWidget

from .models import Post, Comment

class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)
        widgets = { 
                    'text': AdminMartorWidget,
                } 
```
How can I add the markdown toolbar as in Django Admin (the figure1) into my blog editing page? Thanks in advance!

**Comment by agusmakmun** [comment]
If you use it outside django admin, you should include the css & javascript.

> But, Collect included some martor static files to your `STATIC_ROOT` folder.
> `./manage.py collectstatic`

See this demo: https://github.com/agusmakmun/django-markdown-editor/blob/master/martor_demo/app/templates/base.html

**Comment by SkippyHo** [comment]
Thank you!

It works perfectly! This app just awesome!
