### ISSUE TITLE
preview is not displaying correctly for “ordered” and “unordered” list items.

### ISSUE THREAD

**Issue by kfconsultant** [agusmakmun/django-markdown-editor#231]
preview is not displaying correctly for “ordered” and “unordered” list items.

## Details
- OS (Operating System) version: OSX Venture
- Browser and browser version: Chrome Version 120.0.6099.199
- Django version: 4.2.7
- Martor version & theme: 1.6.28

### Steps to reproduce
If you put the following markdown text in the https://markdownlivepreview.com
```
* Item 1
* Item 2
1. Item 1
2. Item 2
    1. Item 3a
    2. Item 3b
```

It displays the following and it is correct:
<img width="771" alt="Screenshot 2024-01-22 at 3 58 55 PM" src="https://github.com/agusmakmun/django-markdown-editor/assets/16928809/71024f5f-ac98-4e11-a4cb-e85b6fcac3ce">

If you use https://pypi.org/project/martor/, it displays all items with bullets only
![Screenshot 2024-01-22 at 4 08 21 PM](https://github.com/agusmakmun/django-markdown-editor/assets/16928809/b13c4e54-851c-450b-a0bd-6eb6605dcaa8)

### The workaround
Put a new line + some text and then it works. Can it be fixed?
![Screenshot 2024-01-22 at 4 15 03 PM](https://github.com/agusmakmun/django-markdown-editor/assets/16928809/4672b878-3100-44ea-aa72-a3a3e2c32083)

**Comment by agusmakmun** [comment]
Hello @kfconsultant thank you for reporting this issue.
We have resolved this issue by adding the `markdown.extensions.sane_lists`.
But there is a limitation in python-markdown itself, where we should add the **new line** for correct result:

| Markdown | Preview |
| ---------- | -------- |
| ![Screenshot 2024-03-29 at 18 06 14](https://github.com/agusmakmun/django-markdown-editor/assets/7134451/0aa8e268-d4f3-44c2-b4fa-0c1b0f1cee07) | ![Screenshot 2024-03-29 at 18 06 25](https://github.com/agusmakmun/django-markdown-editor/assets/7134451/7726ca04-b7b6-4d85-8f41-5ca594b79263) |

Kindly to upgrade your martor package for this fixes:

```
pip install martor --upgrade
```
