### ISSUE TITLE
Django 5 & Python 3.12 support

### ISSUE THREAD

**Issue by ddkasa** [agusmakmun/django-markdown-editor#236]
```
Because no versions of martor match >1.6.37,<2.0.0 and martor (1.6.37) depends on Django (>=3.2,<=4.2.10), martor (>=1.6.37,<2.0.0) requires Django (>=3.2,<=4.2.10).
So, because your project depends on both django (^5.0) and martor (^1.6.37), version solving failed.
```
I am wondering if Django 5 & Python 3.12 support is on the horizon or planned at all?

**Comment by mvaled** [comment]
I have pinned martor to version 1.6.26 because of #210, and it works with Django 5.0.3 without problems. Newer releases of martor have put a cap to Django version (I haven't found any issues in practice).

**Comment by agusmakmun** [comment]
Hello @ddkasa @mvaled we have upgraded the matrix version to compatible with Django 5.0.

Please upgrade the latest version:

```
pip install martor --upgrade
```

https://github.com/agusmakmun/django-markdown-editor/commit/824fa88aa25fe3edc886a0430a9436c70763d709
