### ISSUE TITLE
Django 4.2.11 support

### ISSUE THREAD

**Issue by eriktelepovsky** [agusmakmun/django-markdown-editor#239]
There is a new Django 4.2.11 version. Can you change the Django requirements from <=4.2.10 to at least <5?

https://github.com/agusmakmun/django-markdown-editor/blob/7868518ffdafafe804a1ee77a18750716443861a/requirements.txt#L4C14-L4C22

**Comment by agusmakmun** [comment]
Hello @eriktelepovsky we have compatibility issue while [installing with python 3.9 and 3.10](https://github.com/agusmakmun/django-markdown-editor/commit/b39cb201d782a3765b8e81a2f775842e3fab4888) can you tell which python version did you use?

**Comment by agusmakmun** [comment]
Hello @eriktelepovsky we have upgraded the matrix version to compatible with Django 5.0.

Please upgrade the latest version:

```
pip install martor --upgrade
```

https://github.com/agusmakmun/django-markdown-editor/commit/824fa88aa25fe3edc886a0430a9436c70763d709
