### ISSUE TITLE
How to remove line numbers from margin

### ISSUE THREAD

**Issue by TheConfused** [agusmakmun/django-markdown-editor#24]
Is there a way I can remove line numbers from the left margin of the app? See: [Google group question](https://groups.google.com/forum/#!searchin/ace-discuss/remove$20line$20numbers%7Csort:date/ace-discuss/9o_jv2XWsOM/cooc1MFvCAAJ)

**Comment by TheFoolishKumar** [comment]
Completely removing ace-editor support will also work for me since my project does not need support for writing codes.

**Comment by agusmakmun** [comment]
As following Google group question, you can edit in [these lines](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/static/martor/js/martor.js#L52-L57), to _re-copress_ the javascript file as `martor.min.js` you can use https://jscompress.com.

```javascript
editor.setOptions({
    enableBasicAutocompletion: true,
    enableSnippets: true,
    enableLiveAutocompletion: true,
    enableMultiselect: false,
    showGutter: false // add this line
});
```
