### ISSUE TITLE
Improve documentation for using html

### ISSUE THREAD

**Issue by cafischer** [agusmakmun/django-markdown-editor#242]
I would like to use html in martor text fields in the Django admin. 
I set ALLOWED_HTML_TAGS and ALLOWED_HTML_ATTRIBUTES with the defaults shown in the readme but even a simple `<br>` or `<h1>Test</h1> is just rendered as text in the preview and on the page showing that field with `{{ field | safe_markdown }}`. 
Do I need to enable some specific extenion or some config in MARTOR_ENABLE_CONFIGS or use another template tag?

**Comment by agusmakmun** [comment]
Hello @cafischer we're using [`escape_html`](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/extensions/escape_html.py), I'm not guaranteed the additional `html` tag will be allowed in the markdown editor.

We use both `ALLOWED_HTML_TAGS` and `ALLOWED_HTML_ATTRIBUTES` to minimize the possibility issue on XSS.

I suggest you to create custom extension, such as this https://stackoverflow.com/a/52561618/6396981
Then update the `MARTOR_MARKDOWN_EXTENSIONS` settings.

**Comment by cafischer** [comment]
Ah ok. So in order to use html in the martor fields, disabling martor.extensions.escape_html works.
