### ISSUE TITLE
Stop tagging Django with a less than version.

### ISSUE THREAD

**Issue by adambirds** [agusmakmun/django-markdown-editor#243]
Can we stop tagging Django with a <= to a version as stops us from updating to latest django versions until you have added a new release to this changing the deps requirements. The likelihood of a minor django version breaking martor would be low.

**Comment by adambirds** [comment]
@agusmakmun could we action this?

**Comment by agusmakmun** [comment]
Hello @adambirds, we have removed the less than version from the requirements.txt file, 
Please upgrade your martor.

```console
pip install martor --upgrade
```

**Comment by adambirds** [comment]
Thanks, appreciate it @agusmakmun
