### ISSUE TITLE
A way to display youtube videos while MARTOR_MARKDOWN_SAFE_MODE = True ?

### ISSUE THREAD

**Issue by ThomasDang93** [agusmakmun/django-markdown-editor#29]
Hi there, I recently downloaded 1.2.7 today. I noticed that the editor supports embedded videos, which is great! However, I can only display embedded video when MARTOR_MARKDOWN_SAFE_MODE = False. Is there a way to display video while that value is set to true? 

For my use case, I am developing a blog where the editor is only present in my admin page. Would it be secure to set the safe mode value to False since I am the only one who has access to the markdown editor?

**Comment by agusmakmun** [comment]
By default `MARTOR_MARKDOWN_SAFE_MODE = True`, I have tried with this `True` mode and working fine. 
Does you added this `martor.extensions.mdx_video` to your extension?

```
MARTOR_MARKDOWN_EXTENSIONS = [
    ....

    # Custom markdown extensions.
    'martor.extensions.urlize',
    'martor.extensions.del_ins',    # ~~strikethrough~~ and ++underscores++
    'martor.extensions.mention',    # to parse markdown mention
    'martor.extensions.emoji',      # to parse markdown emoji
    'martor.extensions.mdx_video',  # to parse embed/iframe video
]
```

**Comment by ThomasDang93** [comment]
Yeah, that did the trick. I was initially trying to enter the iframe link of a youtube video, but the markdown editor removes the html. I realized that just entering the shared link of a youtube video will display it properly.
