### ISSUE TITLE
Automatic image orientation

### ISSUE THREAD

**Issue by eriktelepovsky** [agusmakmun/django-markdown-editor#30]
If the uploaded photo has been taken in portrait mode, the preview shows the image in landscape mode. It ignores the EXIF data. Is it possible to fix it somehow?

**Comment by agusmakmun** [comment]
@eriktelepovsky perhaps this can help https://stackoverflow.com/q/51763488/6396981

**Comment by eriktelepovsky** [comment]
Looks promising! Thank you for this.
