### ISSUE TITLE
Bold adds 4 asterisks instead of 2

### ISSUE THREAD

**Issue by jdhurwitz** [agusmakmun/django-markdown-editor#33]
When I type text, then highlight it and press the "B", 4 asterisks surround it instead of two. Is there a way to configure this? 

<img width="694" alt="image" src="https://user-images.githubusercontent.com/9702107/43597425-dbdc5342-9636-11e8-8bde-05ee69a429c3.png">

**Comment by agusmakmun** [comment]
@jdhurwitz the python markdown was parsed with this mode.

- character single `*` for _italic_.
- character double `**` for **bold**.
- if having `***` should parse as **_bold & italic_**

You can see "Markdown Guide" for the columns "Code" and "Or"

![](https://raw.githubusercontent.com/agusmakmun/django-markdown-editor/master/__screenshot/martor-guide.png)

**Comment by jdhurwitz** [comment]
Yes, I'm in agreement with you that two asterisks is how it's supposed to be. However, the package is producing 4 as in my original post. Any idea why this might be?

**Comment by agusmakmun** [comment]
What your operating system?

**Comment by jdhurwitz** [comment]
Mac OS 10.13.6

**Comment by agusmakmun** [comment]
If you use the **bold button toolbar**, does it same?

**Comment by jdhurwitz** [comment]
What do you mean bold button toolbar? If I use the **bold** button on github's markdown toolbar, it works fine and adds 2. The one in django-markdown-editor adds 4.

**Comment by jdhurwitz** [comment]
@agusmakmun  Any ideas, please?

**Comment by jdhurwitz** [comment]
@agusmakmun  figured out the issue. If add stuff to the extra_js section that's duplicated, it will do it twice. Your form's js already handles the functions so there was no need to add stuff in extra_js. Closing both issues.
