### ISSUE TITLE
Resize the Image

### ISSUE THREAD

**Issue by uditvashisht** [agusmakmun/django-markdown-editor#34]
I am trying to save the images to be upload in the post in a local storage. Is it to change the display size of the image at the time of uploading ?

**Comment by agusmakmun** [comment]
@uditvashisht No.. As you can see, we just following default rule for upload mode.

**Comment by agusmakmun** [comment]
@uditvashisht you can disable the image upload button which changing this configuration.

```
MARTOR_ENABLE_CONFIGS = {
    'imgur': 'false',     # to enable/disable imgur/custom uploader.
   ...
} 
```

For the image link button, you can following this options:

1. If you want to remove image link button for all markdown editor in your blog, you can modify this template `templates/martor/toolbar.html`, how?
    1. create new file `martor/toolbar.html` in your own project templates.
    2. copy paste [this html script](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/templates/martor/toolbar.html).
    3. and remove [these lines](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/templates/martor/toolbar.html#L42-L48)

2. If you want to remove only for certain place/editor. you can handle it with javascript, and put this script in your bottom template.

```js
<script>
    $(document).find(".markdown-image-link, .markdown-image-upload").remove();
</script>
```

**Comment by uditvashisht** [comment]
Great.. It worked like a charm. 
I wanted to use the editor at multiple places so i added the css and js in the base.html of my website. Due to which the font of the text on my website changed to a smaller one on its own. any solution to that ?

**Comment by agusmakmun** [comment]
1. You can modify the martor css file `static/martor/css/martor.css`, and compile it to `martor.min.css`. But if you mean is a font in the text editor, as you can see, here we use [ace editor](https://ace.c9.io). so, you should change `fontSize:` in [editor options](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/static/martor/js/martor.js#L52-L57). For example is [like this](https://stackoverflow.com/a/21909788/6396981).

2. Are you using javascript/jquery to render the form? If yes, it similiar with these issues #16 and #15 
    I was stuck in this cases it because the ace editor can't work properly. _I am still waiting for the best solution to handle this case._

**Comment by agusmakmun** [comment]
makesure the fields of both is not _duplicated/same_ field name.

**Comment by agusmakmun** [comment]
related issue: https://github.com/agusmakmun/django-markdown-editor/issues/18
