### ISSUE TITLE
Does id on h* tags are supported ?

### ISSUE THREAD

**Issue by sorasful** [agusmakmun/django-markdown-editor#43]
Hi,

I have multiples titles which are translates as h1, h2 ... But when I try to render, it doesn't add an id attribute on the html tag, which leads me to not having table of content.

Any idea ?

Thanks you :)

**Comment by agusmakmun** [comment]
@sorasful, simply brother, you just need to include `headerid` extension from python markdown.

```python
MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.fenced_code',
    'markdown.extensions.headerid', # add this line

    ....
]
```

for more, you can checkout this https://python-markdown.github.io/extensions/header_id/

**Comment by sorasful** [comment]
Thank you very much !

**Comment by sorasful** [comment]
@agusmakmun , thanks a lot :+1:  !
