### ISSUE TITLE
Urls after bullet points

### ISSUE THREAD

**Issue by olymk2** [agusmakmun/django-markdown-editor#46]
When posting a link after a bullet point the link seems to fail if  : is present in this case thing:3121794 it seems fine when no bullet point is used.

This works 
````
[A thingiverse post](https://www.thingiverse.com/thing:3118584)
[https://www.thingiverse.com/thing:3121794](https://www.thingiverse.com/thing:3121794)
````
vs this which results in a blank url when the page is rendered
````
+ [A thingiverse post](https://www.thingiverse.com/thing:3118584)
+ [https://www.thingiverse.com/thing:3121794](https://www.thingiverse.com/thing:3121794)
````
I believe it happening in urlize but have struggle to track down an exact source, running the above directly through markdown in the repl seems to produce the expected result.

**Comment by agusmakmun** [comment]
@olymk2 Does it still doesn't work for you?
I was tried it at https://python.web.id/pages/egg/, and worked fine..
