### ISSUE TITLE
imgur photo uploads not showing image

### ISSUE THREAD

**Issue by jdhurwitz** [agusmakmun/django-markdown-editor#48]
Created an imgur dev account with my keys and photo uploads worked at first (a couple weeks ago). Now I'm having an issue where the image will get uploaded to imgur and the url to the image will will work if I manually copy-paste it into the browser, but the markdown editor box will show something like the following rather than the image itself: 

<img width="386" alt="image" src="https://user-images.githubusercontent.com/9702107/46241618-939c1280-c371-11e8-891b-77e930f02b40.png">

**Comment by jdhurwitz** [comment]
Any word on this?

**Comment by jdhurwitz** [comment]
@agusmakmun  any thoughts?

**Comment by jdhurwitz** [comment]
So turns out the 403 issue is a problem with Imgur's API. This is not an issue with django-markdown. If you're having this same issue and using localhost, try using your IP address instead. Alternatively, if you're using your IP address like we were, try using localhost.

**Comment by bvermeulen** [comment]
Thanks I had the same issue. Resolved using `localhost:8000` rather than `127.0.01:8000`
