### ISSUE TITLE
Wrong request path to markdown.js

### ISSUE THREAD

**Issue by dismine** [agusmakmun/django-markdown-editor#55]
Hello,
Can someone help me with very weird bug? On production settings `ace.js` makes request to invalid path. Something like this: `https://<domain>/en/patterns/snippets/markdown.js/` where correct path must be `https://<domain>/static/plugins/js/snippets/markdown.js/`. Development server on local machine doesn't produce such a behaviour. Maybe i miss some setting?

**Comment by sodrew** [comment]
Strangely, enough, I'm having a very similar issue when trying to render a martor edit widget when I use the following in my settings.py:

`STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'`

`DEBUG = true`

The URL for markdown.js is ignoring the static files location and is trying to nest within the page structure that it is getting served, while at the same time ace.js is giving me this error:

`Unable to infer path to ace from script src, use ace.config.set...`

It's definitely related to the fact that ManifestStaticFilesStorage is creating separate versioned static files.  I believe the Django Compressor also does something similar with the static files (adding a hash of the version to the filename, and therefore tied to the issue @dismine was having.  I have no conflict with django-sekizai.

All other js and css files are unaffected.
