### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by mark0978** [agusmakmun/django-markdown-editor#60]
Getting no error messages, network panel shows markdownified text being returned, but the actual preview not displaying.  (Button bar is hidden, but the preview panel remains hidden)

**Comment by mark0978** [comment]
The problem was the 2 versions of jQuery on the page.  The {{ form.media }} was including a jQuery and several plugins, then the page itself was wiping out that version of jQuery with the include from there.

The solution was to turn off martor's jQuery and move {{ form.media }} to after the jQuery file had been loaded on the page, something like this

```
{% block javascript %}
    {{ block.super }}
    {{ form.media }}
{% endblock javascript %}
```

And 

```py
# Global martor settings
# Input: string boolean, `true/false`
MARTOR_ENABLE_CONFIGS = {
    ...
    'jquery': 'false',    # to include/revoke jquery (require for admin default django)
    ...
}
```

I put this here to save the next person that has this problem some time.

**Comment by endersonmenezes** [comment]
It's work for me! Thx :+1:

**Comment by saralgyaan** [comment]
Thanks a lot... It worked for me too
