### ISSUE TITLE
Form doesn't load bootstrap

### ISSUE THREAD

**Issue by reyesvicente** [agusmakmun/django-markdown-editor#71]
I triple checked everything on the docs but it doesnt seem to load and preview.

![Screen Shot 2019-06-04 at 8 35 17 PM](https://user-images.githubusercontent.com/45283313/58879610-9fae5000-8708-11e9-9bd5-4271f05c1fe8.png)

Even the preview doesn't show
![Screen Shot 2019-06-04 at 8 38 46 PM](https://user-images.githubusercontent.com/45283313/58879695-cf5d5800-8708-11e9-9451-5e9b00025d33.png)

**Comment by agusmakmun** [comment]
hello @reyesvicente this case was [issued here..](https://github.com/agusmakmun/django-markdown-editor/issues/11)
