### ISSUE TITLE
Pink text on code on template but not on admin

### ISSUE THREAD

**Issue by reyesvicente** [agusmakmun/django-markdown-editor#73]
I'm wondering why it only shows on my newest post.

This one's on the admin:

![admin](https://user-images.githubusercontent.com/45283313/60105388-d1f61f00-9795-11e9-8697-1659410bf9e8.png)

This is on my site:

![site](https://user-images.githubusercontent.com/45283313/60105397-d589a600-9795-11e9-969b-98f03593373a.png)

What could have I missed?

**Comment by agusmakmun** [comment]
I think this problem because the css of this markdown editor is put before your css. So, your css will replacing the previous css.

**Comment by reyesvicente** [comment]
> I think this problem because the css of this markdown editor is put before your css. So, your css will replacing the previous css.

I understand. How can we fix this? I have `{% load martortags %}` on top of my template but can still see bugs on the page. 
![Screen Shot 2019-06-26 at 11 57 32 AM](https://user-images.githubusercontent.com/45283313/60150225-5b473900-980a-11e9-8947-1a1d0204b79d.png)

**Comment by agusmakmun** [comment]
@reyesvicente isn't about `{% load martortags %}`, but it because your css. You can [see this example](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor_demo/app/templates/base.html#L5-L8)

```html
<link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'css/your-css-goes-here.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
```

**Comment by reyesvicente** [comment]
> @reyesvicente isn't about `{% load martortags %}`, but it because your css. You can [see this example](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor_demo/app/templates/base.html#L5-L8)
> 
> ```
> <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
> <link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
> <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
> <link href="{% static 'martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
> 
> <link href="{% static 'css/your-css-goes-here.css' %}" type="text/css" media="all" rel="stylesheet" />
> ```
Thanks. It worked.

Do you have a guide on how to link an s3 storage?

**Comment by agusmakmun** [comment]
@reyesvicente perhaps this tutorial can help you [How to Setup Amazon S3 in a Django Projec](https://simpleisbetterthancomplex.com/tutorial/2017/08/01/how-to-setup-amazon-s3-in-a-django-project.html)
