### ISSUE TITLE
Update custom uploader wiki instructions for Django >=2 compatibility

### ISSUE THREAD

**Issue by allthatilk** [agusmakmun/django-markdown-editor#77]
The current wiki instructions for the custom image uploader functionality could use extra information for changes since Django 2. I would be happy to do this but as it's in the wiki I can't submit a PR to add the changes myself.

**Comment by agusmakmun** [comment]
@allthatilk you can provide it information here, I'll happy to clarity soon.

**Comment by allthatilk** [comment]
For the opening information on the Custom Uploader wiki entry this would be easier to understand:
```
If you want to save images uploaded to your storage, MARTOR also provides a way to handle this by allowing you to use a custom uploader. The scripts below show how you could do this:
```
To support Django 2 for the urls.py script in part 3 it would be good to also add:
```
from yourapp.views import markdown_uploader

urlpatterns = [
    ....
    path(
        'api/uploader/', markdown_uploader, name='markdown_uploader_page'
    ),
]
```
I hope this is useful, if you have any questions or anything let me know 👍

**Comment by agusmakmun** [comment]
Thank so much @allthatilk :+1: 
I'm sorry, my english not really good.
