### ISSUE TITLE
Syntax highlighting not working in template

### ISSUE THREAD

**Issue by adder46** [agusmakmun/django-markdown-editor#97]
I have just come across martor and in short, it's great and it's exactly what I need. However, I'm having an issue with syntax highlighting in my template. Sorry for opening a new issue, but the solutions in [this](https://github.com/agusmakmun/django-markdown-editor/issues/54) issue didn't work for me.

This is my template:
```html
{% load martortags %}
<div class="note-description martor-preview">
    {{ note.description|truncatechars:255|safe_markdown }}
</div>
```
I have also included this (I have tried including it in both the top and the bottom of the page, nothing worked out):
```js
<script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script>
$(document).ready(function() {
    $('pre').each(function(i, block) {
        hljs.highlightBlock(block);
    });
});
</script>
```
..but the [result](http://i.imgur.com/ZWspSa4.png) is not highlighted.

What am I doing wrong and can I somehow overcome this issue?

**Comment by elmcrest** [comment]
hey @adder46 
If you don‘t mind, how did it turn out? I‘m not yet at templates, but still, it‘s a shame the issue is just closed without further info, no offense :)

**Comment by adambirds** [comment]
I am also running into this issue, does anybody have any idea on how to solve?

**Comment by agusmakmun** [comment]
Hello @adambirds, you can refers to this issue: https://github.com/agusmakmun/django-markdown-editor/issues/54#issuecomment-441851084
